openapi: 3.0.0
info:
  title: Vercel SQL Relay
  version: 1.0.0
servers:
  - url: https://eidos-sql-relay.vercel.app
paths:
  /api/sql:
    post:
      operationId: runSQL
      summary: Run SQL query through the Vercel relay
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: "select current_user, current_date;"
      responses:
        '200':
          description: Successful SQL response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                  error:
                    type: object
